// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Table.proto

package dbms.backend.parsers.protobuf;

public final class TableProtoBuf {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dbms_Table_module_descriptor;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dbms_Table_module_Column_module_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_dbms_Table_module_fieldAccessorTable;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_dbms_Table_module_Column_module_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\013Table.proto\022\004dbms\"\274\001\n\014Table_module"
                        + "\022\025\n\r" +
                        "database_name\030\001 \002"
                        + "(\t\022\022\n\ntable_name\030\002 \002(\t\022" +
                        "1\n\007columns\030\003 \003(\0132 .dbms.TableModule"
                        + ".Col" +
                        "umn_module\032N\n\rColumnModule\022\023\n"
                        + "\013column_na" +
                        "me\030\001 \001"
                        + "(\t\022\027\n\017column_dataType\030\002 \001"
                        + "(\t\022\017\n\007ent" +
                        "ries\030\003 \003(\tB.\n\035dbms.backend.parsers"
                        + ".proto" +
                        "bufB\rTableProtoBuf"
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor
                        .InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry
                    assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor
                                    root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_dbms_Table_module_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dbms_Table_module_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_dbms_Table_module_descriptor,
                new java.lang.String[]{"DatabaseName", "TableName",
                        "Columns",});
        internal_static_dbms_Table_module_Column_module_descriptor =
                internal_static_dbms_Table_module_descriptor.getNestedTypes()
                        .get(0);
        internal_static_dbms_Table_module_Column_module_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_dbms_Table_module_Column_module_descriptor,
                new java.lang.String[]{"ColumnName", "ColumnDataType",
                        "Entries",});
    }

    private TableProtoBuf() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface Table_moduleOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dbms.TableModule)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string database_name = 1;</code>
         */
        boolean hasDatabaseName();

        /**
         * <code>required string database_name = 1;</code>
         */
        java.lang.String getDatabaseName();

        /**
         * <code>required string database_name = 1;</code>
         */
        com.google.protobuf.ByteString
        getDatabaseNameBytes();

        /**
         * <code>required string table_name = 2;</code>
         */
        boolean hasTableName();

        /**
         * <code>required string table_name = 2;</code>
         */
        java.lang.String getTableName();

        /**
         * <code>required string table_name = 2;</code>
         */
        com.google.protobuf.ByteString
        getTableNameBytes();

        /**
         * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
         */
        java.util.List<dbms.backend.parsers.protobuf.TableProtoBuf
                .TableModule.ColumnModule>
        getColumnsList();

        /**
         * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
         */
        dbms.backend.parsers.protobuf.TableProtoBuf.TableModule.ColumnModule
        getColumns(int index);

        /**
         * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
         */
        int getColumnsCount();

        /**
         * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
         */
        java.util.List<? extends dbms.backend.parsers.protobuf.TableProtoBuf
                .TableModule.Column_moduleOrBuilder>
        getColumnsOrBuilderList();

        /**
         * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
         */
        dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                .Column_moduleOrBuilder getColumnsOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code dbms.TableModule}
     */
    public static final class TableModule extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:dbms.TableModule)
            Table_moduleOrBuilder {
        public static final int DATABASE_NAME_FIELD_NUMBER = 1;
        public static final int TABLE_NAME_FIELD_NUMBER = 2;
        public static final int COLUMNS_FIELD_NUMBER = 3;
        private static final TableModule defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<TableModule> PARSER =
                new com.google.protobuf.AbstractParser<TableModule>() {
                    public TableModule parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite
                                    extensionRegistry)
                            throws com.google.protobuf
                            .InvalidProtocolBufferException {
                        return new TableModule(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new TableModule(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private java.lang.Object databaseName_;
        private java.lang.Object tableName_;
        private java.util.List<dbms.backend.parsers.protobuf.TableProtoBuf
                .TableModule.ColumnModule> columns_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use TableModule.newBuilder() to construct.
        private TableModule(com.google.protobuf.GeneratedMessage.Builder<?>
                                    builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private TableModule(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet
                    .getDefaultInstance();
        }

        private TableModule(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input
                                    .readBytes();
                            bitField0_ |= 0x00000001;
                            databaseName_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input
                                    .readBytes();
                            bitField0_ |= 0x00000002;
                            tableName_ = bs;
                            break;
                        }
                        case 26: {
                            if (!((mutable_bitField0_ & 0x00000004) ==
                                    0x00000004)) {
                                columns_ = new java.util.ArrayList<dbms
                                        .backend.parsers.protobuf
                                        .TableProtoBuf.TableModule
                                        .ColumnModule>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            columns_.add(input.readMessage(dbms.backend
                                    .parsers.protobuf.TableProtoBuf
                                    .TableModule.ColumnModule.PARSER,
                                    extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    columns_ = java.util.Collections.unmodifiableList(columns_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static TableModule getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return dbms.backend.parsers.protobuf.TableProtoBuf
                    .internal_static_dbms_Table_module_descriptor;
        }

        public static dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
        parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
        parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
        parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
        parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
        parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
        parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
        parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
        parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
        parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
        parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(dbms.backend.parsers.protobuf
                                                 .TableProtoBuf.TableModule
                                                 prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public TableModule getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return dbms.backend.parsers.protobuf.TableProtoBuf
                    .internal_static_dbms_Table_module_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dbms.backend.parsers.protobuf.TableProtoBuf
                                    .TableModule.class, dbms.backend.parsers
                                    .protobuf.TableProtoBuf.TableModule
                                    .Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<TableModule> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required string database_name = 1;</code>
         */
        public boolean hasDatabaseName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string database_name = 1;</code>
         */
        public java.lang.String getDatabaseName() {
            java.lang.Object ref = databaseName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    databaseName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string database_name = 1;</code>
         */
        public com.google.protobuf.ByteString
        getDatabaseNameBytes() {
            java.lang.Object ref = databaseName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                databaseName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>required string table_name = 2;</code>
         */
        public boolean hasTableName() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string table_name = 2;</code>
         */
        public java.lang.String getTableName() {
            java.lang.Object ref = tableName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    tableName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string table_name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTableNameBytes() {
            java.lang.Object ref = tableName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                tableName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
         */
        public java.util.List<dbms.backend.parsers.protobuf.TableProtoBuf
                .TableModule.ColumnModule> getColumnsList() {
            return columns_;
        }

        /**
         * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
         */
        public java.util.List<? extends dbms.backend.parsers.protobuf
                .TableProtoBuf.TableModule.Column_moduleOrBuilder>
        getColumnsOrBuilderList() {
            return columns_;
        }

        /**
         * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
         */
        public int getColumnsCount() {
            return columns_.size();
        }

        /**
         * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
         */
        public dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                .ColumnModule getColumns(int index) {
            return columns_.get(index);
        }

        /**
         * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
         */
        public dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                .Column_moduleOrBuilder getColumnsOrBuilder(
                int index) {
            return columns_.get(index);
        }

        private void initFields() {
            databaseName_ = "";
            tableName_ = "";
            columns_ = java.util.Collections.emptyList();
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasDatabaseName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasTableName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getDatabaseNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getTableNameBytes());
            }
            for (int i = 0; i < columns_.size(); i++) {
                output.writeMessage(3, columns_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getDatabaseNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getTableNameBytes());
            }
            for (int i = 0; i < columns_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, columns_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public interface Column_moduleOrBuilder extends
                // @@protoc_insertion_point(interface_extends:dbms
                // .TableModule.ColumnModule)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>optional string column_name = 1;</code>
             */
            boolean hasColumnName();

            /**
             * <code>optional string column_name = 1;</code>
             */
            java.lang.String getColumnName();

            /**
             * <code>optional string column_name = 1;</code>
             */
            com.google.protobuf.ByteString
            getColumnNameBytes();

            /**
             * <code>optional string column_dataType = 2;</code>
             */
            boolean hasColumnDataType();

            /**
             * <code>optional string column_dataType = 2;</code>
             */
            java.lang.String getColumnDataType();

            /**
             * <code>optional string column_dataType = 2;</code>
             */
            com.google.protobuf.ByteString
            getColumnDataTypeBytes();

            /**
             * <code>repeated string entries = 3;</code>
             */
            com.google.protobuf.ProtocolStringList
            getEntriesList();

            /**
             * <code>repeated string entries = 3;</code>
             */
            int getEntriesCount();

            /**
             * <code>repeated string entries = 3;</code>
             */
            java.lang.String getEntries(int index);

            /**
             * <code>repeated string entries = 3;</code>
             */
            com.google.protobuf.ByteString
            getEntriesBytes(int index);
        }

        /**
         * Protobuf type {@code dbms.TableModule.ColumnModule}
         */
        public static final class ColumnModule extends
                com.google.protobuf.GeneratedMessage implements
                // @@protoc_insertion_point(message_implements:dbms
                // .TableModule.ColumnModule)
                Column_moduleOrBuilder {
            public static final int COLUMN_NAME_FIELD_NUMBER = 1;
            public static final int COLUMN_DATATYPE_FIELD_NUMBER = 2;
            public static final int ENTRIES_FIELD_NUMBER = 3;
            private static final ColumnModule defaultInstance;
            private static final long serialVersionUID = 0L;
            public static com.google.protobuf.Parser<ColumnModule> PARSER =
                    new com.google.protobuf.AbstractParser<ColumnModule>() {
                        public ColumnModule parsePartialFrom(
                                com.google.protobuf.CodedInputStream input,
                                com.google.protobuf.ExtensionRegistryLite
                                        extensionRegistry)
                                throws com.google.protobuf
                                .InvalidProtocolBufferException {
                            return new ColumnModule(input, extensionRegistry);
                        }
                    };

            static {
                defaultInstance = new ColumnModule(true);
                defaultInstance.initFields();
            }

            private final com.google.protobuf.UnknownFieldSet unknownFields;
            private int bitField0_;
            private java.lang.Object columnName_;
            private java.lang.Object columnDataType_;
            private com.google.protobuf.LazyStringList entries_;
            private byte memoizedIsInitialized = -1;
            private int memoizedSerializedSize = -1;

            // Use ColumnModule.newBuilder() to construct.
            private ColumnModule(com.google.protobuf.GeneratedMessage
                                         .Builder<?> builder) {
                super(builder);
                this.unknownFields = builder.getUnknownFields();
            }

            private ColumnModule(boolean noInit) {
                this.unknownFields = com.google.protobuf.UnknownFieldSet
                        .getDefaultInstance();
            }

            private ColumnModule(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                initFields();
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            default: {
                                if (!parseUnknownField(input, unknownFields,
                                        extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                            case 10: {
                                com.google.protobuf.ByteString bs = input
                                        .readBytes();
                                bitField0_ |= 0x00000001;
                                columnName_ = bs;
                                break;
                            }
                            case 18: {
                                com.google.protobuf.ByteString bs = input
                                        .readBytes();
                                bitField0_ |= 0x00000002;
                                columnDataType_ = bs;
                                break;
                            }
                            case 26: {
                                com.google.protobuf.ByteString bs = input
                                        .readBytes();
                                if (!((mutable_bitField0_ & 0x00000004) ==
                                        0x00000004)) {
                                    entries_ = new com.google.protobuf
                                            .LazyStringArrayList();
                                    mutable_bitField0_ |= 0x00000004;
                                }
                                entries_.add(bs);
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf
                            .InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(this);
                } finally {
                    if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                        entries_ = entries_.getUnmodifiableView();
                    }
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            public static ColumnModule getDefaultInstance() {
                return defaultInstance;
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dbms.backend.parsers.protobuf.TableProtoBuf
                        .internal_static_dbms_Table_module_Column_module_descriptor;
            }

            public static dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return PARSER.parseFrom(input);
            }

            public static dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }

            public static dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input);
            }

            public static dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input, extensionRegistry);
            }

            public static dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return PARSER.parseFrom(input);
            }

            public static dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }

            public static Builder newBuilder() {
                return Builder.create();
            }

            public static Builder newBuilder(dbms.backend.parsers.protobuf
                                                     .TableProtoBuf
                                                     .TableModule
                                                     .ColumnModule prototype) {
                return newBuilder().mergeFrom(prototype);
            }

            public ColumnModule getDefaultInstanceForType() {
                return defaultInstance;
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dbms.backend.parsers.protobuf.TableProtoBuf
                        .internal_static_dbms_Table_module_Column_module_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dbms.backend.parsers.protobuf.TableProtoBuf
                                        .TableModule.ColumnModule.class, dbms
                                        .backend.parsers.protobuf
                                        .TableProtoBuf.TableModule
                                        .ColumnModule.Builder.class);
            }

            @java.lang.Override
            public com.google.protobuf.Parser<ColumnModule> getParserForType() {
                return PARSER;
            }

            /**
             * <code>optional string column_name = 1;</code>
             */
            public boolean hasColumnName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string column_name = 1;</code>
             */
            public java.lang.String getColumnName() {
                java.lang.Object ref = columnName_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        columnName_ = s;
                    }
                    return s;
                }
            }

            /**
             * <code>optional string column_name = 1;</code>
             */
            public com.google.protobuf.ByteString
            getColumnNameBytes() {
                java.lang.Object ref = columnName_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    columnName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string column_dataType = 2;</code>
             */
            public boolean hasColumnDataType() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional string column_dataType = 2;</code>
             */
            public java.lang.String getColumnDataType() {
                java.lang.Object ref = columnDataType_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        columnDataType_ = s;
                    }
                    return s;
                }
            }

            /**
             * <code>optional string column_dataType = 2;</code>
             */
            public com.google.protobuf.ByteString
            getColumnDataTypeBytes() {
                java.lang.Object ref = columnDataType_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    columnDataType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>repeated string entries = 3;</code>
             */
            public com.google.protobuf.ProtocolStringList
            getEntriesList() {
                return entries_;
            }

            /**
             * <code>repeated string entries = 3;</code>
             */
            public int getEntriesCount() {
                return entries_.size();
            }

            /**
             * <code>repeated string entries = 3;</code>
             */
            public java.lang.String getEntries(int index) {
                return entries_.get(index);
            }

            /**
             * <code>repeated string entries = 3;</code>
             */
            public com.google.protobuf.ByteString
            getEntriesBytes(int index) {
                return entries_.getByteString(index);
            }

            private void initFields() {
                columnName_ = "";
                columnDataType_ = "";
                entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            }

            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                getSerializedSize();
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    output.writeBytes(1, getColumnNameBytes());
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    output.writeBytes(2, getColumnDataTypeBytes());
                }
                for (int i = 0; i < entries_.size(); i++) {
                    output.writeBytes(3, entries_.getByteString(i));
                }
                getUnknownFields().writeTo(output);
            }

            public int getSerializedSize() {
                int size = memoizedSerializedSize;
                if (size != -1) return size;

                size = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(1, getColumnNameBytes());
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(2, getColumnDataTypeBytes());
                }
                {
                    int dataSize = 0;
                    for (int i = 0; i < entries_.size(); i++) {
                        dataSize += com.google.protobuf.CodedOutputStream
                                .computeBytesSizeNoTag(entries_.getByteString
                                        (i));
                    }
                    size += dataSize;
                    size += 1 * getEntriesList().size();
                }
                size += getUnknownFields().getSerializedSize();
                memoizedSerializedSize = size;
                return size;
            }

            @java.lang.Override
            protected java.lang.Object writeReplace()
                    throws java.io.ObjectStreamException {
                return super.writeReplace();
            }

            public Builder newBuilderForType() {
                return newBuilder();
            }

            public Builder toBuilder() {
                return newBuilder(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            /**
             * Protobuf type {@code dbms.TableModule.ColumnModule}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessage.Builder<Builder>
                    implements
                    // @@protoc_insertion_point(builder_implements:dbms
                    // .TableModule.ColumnModule)
                    dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                            .Column_moduleOrBuilder {
                private int bitField0_;
                private java.lang.Object columnName_ = "";
                private java.lang.Object columnDataType_ = "";
                private com.google.protobuf.LazyStringList entries_ = com
                        .google.protobuf.LazyStringArrayList.EMPTY;

                // Construct using dbms.backend.parsers.protobuf
                // .TableProtoBuf.TableModule.ColumnModule.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessage.BuilderParent
                                parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return dbms.backend.parsers.protobuf.TableProtoBuf
                            .internal_static_dbms_Table_module_Column_module_descriptor;
                }

                private static Builder create() {
                    return new Builder();
                }

                protected com.google.protobuf.GeneratedMessage
                        .FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return dbms.backend.parsers.protobuf.TableProtoBuf
                            .internal_static_dbms_Table_module_Column_module_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    dbms.backend.parsers.protobuf
                                            .TableProtoBuf.TableModule
                                            .ColumnModule.class, dbms.backend
                                            .parsers.protobuf.TableProtoBuf
                                            .TableModule.ColumnModule.Builder
                                            .class);
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage
                            .alwaysUseFieldBuilders) {
                    }
                }

                public Builder clear() {
                    super.clear();
                    columnName_ = "";
                    bitField0_ = (bitField0_ & ~0x00000001);
                    columnDataType_ = "";
                    bitField0_ = (bitField0_ & ~0x00000002);
                    entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                    bitField0_ = (bitField0_ & ~0x00000004);
                    return this;
                }

                public Builder clone() {
                    return create().mergeFrom(buildPartial());
                }

                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return dbms.backend.parsers.protobuf.TableProtoBuf
                            .internal_static_dbms_Table_module_Column_module_descriptor;
                }

                public dbms.backend.parsers.protobuf.TableProtoBuf
                        .TableModule.ColumnModule getDefaultInstanceForType() {
                    return dbms.backend.parsers.protobuf.TableProtoBuf
                            .TableModule.ColumnModule.getDefaultInstance();
                }

                public dbms.backend.parsers.protobuf.TableProtoBuf
                        .TableModule.ColumnModule build() {
                    dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                            .ColumnModule result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                public dbms.backend.parsers.protobuf.TableProtoBuf
                        .TableModule.ColumnModule buildPartial() {
                    dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                            .ColumnModule result = new dbms.backend.parsers
                            .protobuf.TableProtoBuf.TableModule.ColumnModule
                            (this);
                    int from_bitField0_ = bitField0_;
                    int to_bitField0_ = 0;
                    if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                        to_bitField0_ |= 0x00000001;
                    }
                    result.columnName_ = columnName_;
                    if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                        to_bitField0_ |= 0x00000002;
                    }
                    result.columnDataType_ = columnDataType_;
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        entries_ = entries_.getUnmodifiableView();
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.entries_ = entries_;
                    result.bitField0_ = to_bitField0_;
                    onBuilt();
                    return result;
                }

                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof dbms.backend.parsers.protobuf
                            .TableProtoBuf.TableModule.ColumnModule) {
                        return mergeFrom((dbms.backend.parsers.protobuf
                                .TableProtoBuf.TableModule.ColumnModule) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(dbms.backend.parsers.protobuf
                                                 .TableProtoBuf.TableModule
                                                 .ColumnModule other) {
                    if (other == dbms.backend.parsers.protobuf.TableProtoBuf
                            .TableModule.ColumnModule.getDefaultInstance())
                        return this;
                    if (other.hasColumnName()) {
                        bitField0_ |= 0x00000001;
                        columnName_ = other.columnName_;
                        onChanged();
                    }
                    if (other.hasColumnDataType()) {
                        bitField0_ |= 0x00000002;
                        columnDataType_ = other.columnDataType_;
                        onChanged();
                    }
                    if (!other.entries_.isEmpty()) {
                        if (entries_.isEmpty()) {
                            entries_ = other.entries_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureEntriesIsMutable();
                            entries_.addAll(other.entries_);
                        }
                        onChanged();
                    }
                    this.mergeUnknownFields(other.getUnknownFields());
                    return this;
                }

                public final boolean isInitialized() {
                    return true;
                }

                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite
                                extensionRegistry)
                        throws java.io.IOException {
                    dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                            .ColumnModule parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input,
                                extensionRegistry);
                    } catch (com.google.protobuf
                            .InvalidProtocolBufferException e) {
                        parsedMessage = (dbms.backend.parsers.protobuf
                                .TableProtoBuf.TableModule.ColumnModule) e
                                .getUnfinishedMessage();
                        throw e;
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                /**
                 * <code>optional string column_name = 1;</code>
                 */
                public boolean hasColumnName() {
                    return ((bitField0_ & 0x00000001) == 0x00000001);
                }

                /**
                 * <code>optional string column_name = 1;</code>
                 */
                public java.lang.String getColumnName() {
                    java.lang.Object ref = columnName_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            columnName_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }

                /**
                 * <code>optional string column_name = 1;</code>
                 */
                public Builder setColumnName(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    columnName_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string column_name = 1;</code>
                 */
                public com.google.protobuf.ByteString
                getColumnNameBytes() {
                    java.lang.Object ref = columnName_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        columnName_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>optional string column_name = 1;</code>
                 */
                public Builder setColumnNameBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    columnName_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string column_name = 1;</code>
                 */
                public Builder clearColumnName() {
                    bitField0_ = (bitField0_ & ~0x00000001);
                    columnName_ = getDefaultInstance().getColumnName();
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string column_dataType = 2;</code>
                 */
                public boolean hasColumnDataType() {
                    return ((bitField0_ & 0x00000002) == 0x00000002);
                }

                /**
                 * <code>optional string column_dataType = 2;</code>
                 */
                public java.lang.String getColumnDataType() {
                    java.lang.Object ref = columnDataType_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            columnDataType_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }

                /**
                 * <code>optional string column_dataType = 2;</code>
                 */
                public Builder setColumnDataType(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000002;
                    columnDataType_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string column_dataType = 2;</code>
                 */
                public com.google.protobuf.ByteString
                getColumnDataTypeBytes() {
                    java.lang.Object ref = columnDataType_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        columnDataType_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>optional string column_dataType = 2;</code>
                 */
                public Builder setColumnDataTypeBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000002;
                    columnDataType_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string column_dataType = 2;</code>
                 */
                public Builder clearColumnDataType() {
                    bitField0_ = (bitField0_ & ~0x00000002);
                    columnDataType_ = getDefaultInstance().getColumnDataType();
                    onChanged();
                    return this;
                }

                private void ensureEntriesIsMutable() {
                    if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                        entries_ = new com.google.protobuf
                                .LazyStringArrayList(entries_);
                        bitField0_ |= 0x00000004;
                    }
                }

                /**
                 * <code>repeated string entries = 3;</code>
                 */
                public com.google.protobuf.ProtocolStringList
                getEntriesList() {
                    return entries_.getUnmodifiableView();
                }

                /**
                 * <code>repeated string entries = 3;</code>
                 */
                public int getEntriesCount() {
                    return entries_.size();
                }

                /**
                 * <code>repeated string entries = 3;</code>
                 */
                public java.lang.String getEntries(int index) {
                    return entries_.get(index);
                }

                /**
                 * <code>repeated string entries = 3;</code>
                 */
                public com.google.protobuf.ByteString
                getEntriesBytes(int index) {
                    return entries_.getByteString(index);
                }

                /**
                 * <code>repeated string entries = 3;</code>
                 */
                public Builder setEntries(
                        int index, java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureEntriesIsMutable();
                    entries_.set(index, value);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string entries = 3;</code>
                 */
                public Builder addEntries(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureEntriesIsMutable();
                    entries_.add(value);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string entries = 3;</code>
                 */
                public Builder addAllEntries(
                        java.lang.Iterable<java.lang.String> values) {
                    ensureEntriesIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, entries_);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string entries = 3;</code>
                 */
                public Builder clearEntries() {
                    entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string entries = 3;</code>
                 */
                public Builder addEntriesBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureEntriesIsMutable();
                    entries_.add(value);
                    onChanged();
                    return this;
                }

                // @@protoc_insertion_point(builder_scope:dbms.TableModule
                // .ColumnModule)
            }

            // @@protoc_insertion_point(class_scope:dbms.TableModule
            // .ColumnModule)
        }

        /**
         * Protobuf type {@code dbms.TableModule}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dbms.TableModule)
                dbms.backend.parsers.protobuf.TableProtoBuf
                        .Table_moduleOrBuilder {
            private int bitField0_;
            private java.lang.Object databaseName_ = "";
            private java.lang.Object tableName_ = "";
            private java.util.List<dbms.backend.parsers.protobuf
                    .TableProtoBuf.TableModule.ColumnModule> columns_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilder<
                    dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                            .ColumnModule, dbms.backend.parsers.protobuf
                    .TableProtoBuf.TableModule.ColumnModule.Builder, dbms
                    .backend.parsers.protobuf.TableProtoBuf.TableModule
                    .Column_moduleOrBuilder> columnsBuilder_;

            // Construct using dbms.backend.parsers.protobuf.TableProtoBuf
            // .TableModule.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dbms.backend.parsers.protobuf.TableProtoBuf
                        .internal_static_dbms_Table_module_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dbms.backend.parsers.protobuf.TableProtoBuf
                        .internal_static_dbms_Table_module_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dbms.backend.parsers.protobuf.TableProtoBuf
                                        .TableModule.class, dbms.backend
                                        .parsers.protobuf.TableProtoBuf
                                        .TableModule.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage
                        .alwaysUseFieldBuilders) {
                    getColumnsFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                databaseName_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                tableName_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                if (columnsBuilder_ == null) {
                    columns_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    columnsBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return dbms.backend.parsers.protobuf.TableProtoBuf
                        .internal_static_dbms_Table_module_descriptor;
            }

            public dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
            getDefaultInstanceForType() {
                return dbms.backend.parsers.protobuf.TableProtoBuf
                        .TableModule.getDefaultInstance();
            }

            public dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
            build() {
                dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                        result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
            buildPartial() {
                dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                        result = new dbms.backend.parsers.protobuf
                        .TableProtoBuf.TableModule(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.databaseName_ = databaseName_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.tableName_ = tableName_;
                if (columnsBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        columns_ = java.util.Collections.unmodifiableList
                                (columns_);
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.columns_ = columns_;
                } else {
                    result.columns_ = columnsBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dbms.backend.parsers.protobuf
                        .TableProtoBuf.TableModule) {
                    return mergeFrom((dbms.backend.parsers.protobuf
                            .TableProtoBuf.TableModule) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dbms.backend.parsers.protobuf
                                             .TableProtoBuf.TableModule other) {
                if (other == dbms.backend.parsers.protobuf.TableProtoBuf
                        .TableModule.getDefaultInstance())
                    return this;
                if (other.hasDatabaseName()) {
                    bitField0_ |= 0x00000001;
                    databaseName_ = other.databaseName_;
                    onChanged();
                }
                if (other.hasTableName()) {
                    bitField0_ |= 0x00000002;
                    tableName_ = other.tableName_;
                    onChanged();
                }
                if (columnsBuilder_ == null) {
                    if (!other.columns_.isEmpty()) {
                        if (columns_.isEmpty()) {
                            columns_ = other.columns_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureColumnsIsMutable();
                            columns_.addAll(other.columns_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.columns_.isEmpty()) {
                        if (columnsBuilder_.isEmpty()) {
                            columnsBuilder_.dispose();
                            columnsBuilder_ = null;
                            columns_ = other.columns_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                            columnsBuilder_ =
                                    com.google.protobuf.GeneratedMessage
                                            .alwaysUseFieldBuilders ?
                                            getColumnsFieldBuilder() : null;
                        } else {
                            columnsBuilder_.addAllMessages(other.columns_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasDatabaseName()) {

                    return false;
                }
                if (!hasTableName()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                        parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input,
                            extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (dbms.backend.parsers.protobuf
                            .TableProtoBuf.TableModule) e
                            .getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required string database_name = 1;</code>
             */
            public boolean hasDatabaseName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string database_name = 1;</code>
             */
            public java.lang.String getDatabaseName() {
                java.lang.Object ref = databaseName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        databaseName_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string database_name = 1;</code>
             */
            public Builder setDatabaseName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                databaseName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string database_name = 1;</code>
             */
            public com.google.protobuf.ByteString
            getDatabaseNameBytes() {
                java.lang.Object ref = databaseName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    databaseName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string database_name = 1;</code>
             */
            public Builder setDatabaseNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                databaseName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string database_name = 1;</code>
             */
            public Builder clearDatabaseName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                databaseName_ = getDefaultInstance().getDatabaseName();
                onChanged();
                return this;
            }

            /**
             * <code>required string table_name = 2;</code>
             */
            public boolean hasTableName() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string table_name = 2;</code>
             */
            public java.lang.String getTableName() {
                java.lang.Object ref = tableName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        tableName_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string table_name = 2;</code>
             */
            public Builder setTableName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                tableName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string table_name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTableNameBytes() {
                java.lang.Object ref = tableName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    tableName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string table_name = 2;</code>
             */
            public Builder setTableNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                tableName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string table_name = 2;</code>
             */
            public Builder clearTableName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                tableName_ = getDefaultInstance().getTableName();
                onChanged();
                return this;
            }

            private void ensureColumnsIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    columns_ = new java.util.ArrayList<dbms.backend.parsers
                            .protobuf.TableProtoBuf.TableModule.ColumnModule>
                            (columns_);
                    bitField0_ |= 0x00000004;
                }
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public java.util.List<dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule> getColumnsList() {
                if (columnsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(columns_);
                } else {
                    return columnsBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public int getColumnsCount() {
                if (columnsBuilder_ == null) {
                    return columns_.size();
                } else {
                    return columnsBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                    .ColumnModule getColumns(int index) {
                if (columnsBuilder_ == null) {
                    return columns_.get(index);
                } else {
                    return columnsBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public Builder setColumns(
                    int index, dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule value) {
                if (columnsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureColumnsIsMutable();
                    columns_.set(index, value);
                    onChanged();
                } else {
                    columnsBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public Builder setColumns(
                    int index, dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule.Builder builderForValue) {
                if (columnsBuilder_ == null) {
                    ensureColumnsIsMutable();
                    columns_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    columnsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public Builder addColumns(dbms.backend.parsers.protobuf
                                              .TableProtoBuf.TableModule
                                              .ColumnModule value) {
                if (columnsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureColumnsIsMutable();
                    columns_.add(value);
                    onChanged();
                } else {
                    columnsBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public Builder addColumns(
                    int index, dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule value) {
                if (columnsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureColumnsIsMutable();
                    columns_.add(index, value);
                    onChanged();
                } else {
                    columnsBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public Builder addColumns(
                    dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                            .ColumnModule.Builder builderForValue) {
                if (columnsBuilder_ == null) {
                    ensureColumnsIsMutable();
                    columns_.add(builderForValue.build());
                    onChanged();
                } else {
                    columnsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public Builder addColumns(
                    int index, dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule.Builder builderForValue) {
                if (columnsBuilder_ == null) {
                    ensureColumnsIsMutable();
                    columns_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    columnsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public Builder addAllColumns(
                    java.lang.Iterable<? extends dbms.backend.parsers
                            .protobuf.TableProtoBuf.TableModule.ColumnModule>
                            values) {
                if (columnsBuilder_ == null) {
                    ensureColumnsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, columns_);
                    onChanged();
                } else {
                    columnsBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public Builder clearColumns() {
                if (columnsBuilder_ == null) {
                    columns_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                } else {
                    columnsBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public Builder removeColumns(int index) {
                if (columnsBuilder_ == null) {
                    ensureColumnsIsMutable();
                    columns_.remove(index);
                    onChanged();
                } else {
                    columnsBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                    .ColumnModule.Builder getColumnsBuilder(
                    int index) {
                return getColumnsFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                    .Column_moduleOrBuilder getColumnsOrBuilder(
                    int index) {
                if (columnsBuilder_ == null) {
                    return columns_.get(index);
                } else {
                    return columnsBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public java.util.List<? extends dbms.backend.parsers.protobuf
                    .TableProtoBuf.TableModule.Column_moduleOrBuilder>
            getColumnsOrBuilderList() {
                if (columnsBuilder_ != null) {
                    return columnsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(columns_);
                }
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                    .ColumnModule.Builder addColumnsBuilder() {
                return getColumnsFieldBuilder().addBuilder(
                        dbms.backend.parsers.protobuf.TableProtoBuf
                                .TableModule.ColumnModule.getDefaultInstance());
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                    .ColumnModule.Builder addColumnsBuilder(
                    int index) {
                return getColumnsFieldBuilder().addBuilder(
                        index, dbms.backend.parsers.protobuf.TableProtoBuf
                                .TableModule.ColumnModule.getDefaultInstance());
            }

            /**
             * <code>repeated .dbms.TableModule.ColumnModule columns = 3;</code>
             */
            public java.util.List<dbms.backend.parsers.protobuf.TableProtoBuf
                    .TableModule.ColumnModule.Builder>
            getColumnsBuilderList() {
                return getColumnsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    dbms.backend.parsers.protobuf.TableProtoBuf.TableModule
                            .ColumnModule, dbms.backend.parsers.protobuf
                    .TableProtoBuf.TableModule.ColumnModule.Builder, dbms
                    .backend.parsers.protobuf.TableProtoBuf.TableModule
                    .Column_moduleOrBuilder>
            getColumnsFieldBuilder() {
                if (columnsBuilder_ == null) {
                    columnsBuilder_ = new com.google.protobuf
                            .RepeatedFieldBuilder<
                            dbms.backend.parsers.protobuf.TableProtoBuf
                                    .TableModule.ColumnModule, dbms.backend
                            .parsers.protobuf.TableProtoBuf.TableModule
                            .ColumnModule.Builder, dbms.backend.parsers
                            .protobuf.TableProtoBuf.TableModule
                            .Column_moduleOrBuilder>(
                            columns_,
                            ((bitField0_ & 0x00000004) == 0x00000004),
                            getParentForChildren(),
                            isClean());
                    columns_ = null;
                }
                return columnsBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:dbms.TableModule)
        }

        // @@protoc_insertion_point(class_scope:dbms.TableModule)
    }

    // @@protoc_insertion_point(outer_class_scope)
}